### ISSUE TITLE
It seems that pyenv is not working on MacOS

### ISSUE THREAD

**Issue by ido777** [digital-plumbers-union/rules_pyenv#8]
in the WORKSPACE I have

`
pyenv_install(
    # For an in-build runtime,
    name = "in-build-python-3.9.7",
    py2 = "2.7.18",
    py3 = "3.9.7",
)

pyenv_install(
    # For host python,
    name = "host-python-3.9.7",
    hermetic = False,
    py2 = "2.7.18",
    py3 = "3.9.6",
)
`

when I run 
bazel test //my_project/...
I am getting:
ERROR: An error occurred during the fetch of repository 'in-build-python-3.9.7':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_x/e415fe5bd55f40cf1f7d9331d349cada/external/dpu_rules_pyenv/pyenv/defs.bzl", line 168, column 20, in _pyenv_install_impl
		_install_python(repository_ctx, py3)
	File "/private/var/tmp/_bazel_x/e415fe5bd55f40cf1f7d9331d349cada/external/dpu_rules_pyenv/pyenv/defs.bzl", line 132, column 13, in _install_python
		fail("pyenv failed to install version %s" % version + res.stdout + res.stderr)
Error in fail: pyenv failed to install version 3.9.7python-build: definition not found: 3.9.7 

But when I do 
pyenv versions
I am getting 
  system
  3.9.5
  3.9.6
* 3.9.7 (set by /Users/...)

**Comment by lazcamus** [comment]
It's likely that the old version of pyenv baked into rules_pyenv doesn't support Python version 3.9.7.

In my WORKSPACE I apply 2 of the pending PRs from this repo:
```
http_archive(
    name = "dpu_rules_pyenv",
    patch_args = ["-p1"],
    patches = [
        "//build/patch:rules_pyenv-2.2.4.patch",
        "//build/patch:rules_pyenv_py3-only.patch",
    ],
    sha256 = "d057168a757efa74e6345edd4776a1c0f38134c2d48eea4f3ef4783e1ea2cb0f",
    strip_prefix = "rules_pyenv-0.1.4",
    urls = ["https://github.com/digital-plumbers-union/rules_pyenv/archive/v0.1.4.tar.gz"],
)
```

and in build/patch/BUILD:
```
exports_files([
    "rules_pyenv_py3-only.patch",
    "rules_pyenv-2.2.4.patch",
])
```
and the actual patch files are pulled from git for each

**Comment by ddlees** [comment]
@ido777 I merged the outstanding PRs and cut a new release. Please let us know if the new release resolved your problem.
